### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by cyouakari** [YukiCoco/YukiDrive#28]
环境：
E5 开发者版全局管理员账号
自建 web 应用（委托的方式，代表管理员已授权）
web 应用中的重定向 URI
http://localhost:53682/
http://localhost:1273/api/admin/bind/new

备注：微软政策 
自 2020 年 11 月 9 日起，最终用户将不再能够同意未经认证的发布者新注册的多租户应用。  【添加 MPN ID 以验证发布者】
处理方式：新注册的应用如果使用多租户模式（单租户只针对本租户内的账号支持），需要进行认证，参考相关文档 ,针对2020年11月9日之前注册的Web 应用添加多个重定向 URL，于是将自定义 URL 进行了添加

问题：
1.认证通过，添加 OneDrive 成功，添加 SharePoint 失败，无论对 SharePoint 进行添加与否，重启后错误日志

Log:

开始启动程序...
Unhandled exception. System.AggregateException: One or more errors occurred. (You are trying to acquire a token silently using a login hint. No account was found in the token cache having this login hint.)
 ---> MSAL.NetCore.4.9.0.0.MsalUiRequiredException:
        ErrorCode: no_account_for_login_hint
Microsoft.Identity.Client.MsalUiRequiredException: You are trying to acquire a token silently using a login hint. No account was found in the token cache having this login hint.
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.GetSingleAccountForLoginHintAsync(String loginHint)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.GetAccountFromParamsOrLoginHintAsync(AcquireTokenSilentParameters silentParameters)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.PreRunAsync()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
        StatusCode: 0
        ResponseBody:
        Headers:
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YukiDrive.Services.TokenService..ctor()
   at YukiDrive.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at YukiDrive.Program.Main(String[] args)

**Comment by YukiCoco** [comment]
是否在 Azure 给了 `Sites.ReadWrite.All` 权限？

**Comment by cyouakari** [comment]
> 是否在 Azure 给了 `Sites.ReadWrite.All` 权限？

是的，给了此权限

**Comment by YukiCoco** [comment]
已解决

**Comment by Micraow** [comment]
啊？你是怎么获得认证的？为什么我的MPN ID它显示不存在？还有，合作伙伴关系是不是要得有一个公司才能申请啊？
